"""add cascade delete

Revision ID: fe603a6d6e93
Revises: 454cddebeaba
Create Date: 2024-03-12 21:57:02.339146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe603a6d6e93'
down_revision: Union[str, None] = '454cddebeaba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expanses_category_expanse_id_fkey', 'expanses', type_='foreignkey')
    op.create_foreign_key(None, 'expanses', 'categories_expanse', ['category_expanse_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('incomes_category_income_id_fkey', 'incomes', type_='foreignkey')
    op.create_foreign_key(None, 'incomes', 'categories_income', ['category_income_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.create_foreign_key('incomes_category_income_id_fkey', 'incomes', 'categories_income', ['category_income_id'], ['id'])
    op.drop_constraint(None, 'expanses', type_='foreignkey')
    op.create_foreign_key('expanses_category_expanse_id_fkey', 'expanses', 'categories_expanse', ['category_expanse_id'], ['id'])
    # ### end Alembic commands ###
