"""third

Revision ID: 1f2f8e61062d
Revises: e8a2e3286a67
Create Date: 2024-02-17 21:37:34.374469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2f8e61062d'
down_revision: Union[str, None] = 'e8a2e3286a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expanses', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('incomes', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'date')
    op.drop_column('expanses', 'date')
    # ### end Alembic commands ###
